### ISSUE TITLE
Madcow weapons has a script error 

### ISSUE THREAD

**Issue by Bryantdl7** [Darkstorm-Servers/Development-tracker#16]
[darkstorm-madcow] addons/darkstorm-madcow/lua/weapons/weapon_mad_base/shared.lua:718: Tried to use a NULL entity!
  1. __index - [C]:-1
   2. unknown - addons/darkstorm-madcow/lua/weapons/weapon_mad_base/shared.lua:718

**Comment by hounddogie** [comment]
Should be fixed, uploaded bugfix to server. Please test.

**Comment by Bryantdl7** [comment]
moving these to the proper repro for the addon
