### ISSUE TITLE
Fix Utime SQL error handling logic

### ISSUE THREAD

**Issue by Bryantdl7** [Darkstorm-Servers/Development-tracker#8]
**Describe the bug**
If the SQL server goes offline due to rate limiting or a network drop at the serverside all players will have 0 hours, and when the connection comes back up their hours will get replaced with 0

**To Reproduce**
1. Run the utime SQL addon
2. disconnect internet for a significant time 
3. have a player join 
4. their hours will be 0 

**Expected behavior**
addon simply checks if the server is back online, or does something else?

**Garry's Mod Branch (please complete the following information):**
Any

**Additional context**
This will be a tricky one to solve... we would need an entire local copy of the SQLite to solve this at least from my perspective

**Comment by hounddogie** [comment]
What file does the SQL logic occur at?
